spring:
  # PostgreSQL DB ??
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.basic.postreSQL.vo

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
